import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Helper to pick an icon based on test name / method keywords
function getIcon(name: string, method: string): string {
  const n = name.toLowerCase();
  const m = method.toLowerCase();
  if (n.includes("blood") || n.includes("cbc") || n.includes("hemoglobin") || n.includes("hematology") || n.includes("rbc") || n.includes("wbc") || n.includes("platelet") || n.includes("hba1c") || n.includes("hb ") || n.includes("erythrocyte") || n.includes("reticulocyte") || n.includes("bleeding") || n.includes("clotting") || n.includes("prothrombin") || n.includes("aptt") || n.includes("fibrinogen") || n.includes("coagul") || n.includes("d-dimer") || n.includes("fdp") || n.includes("apla") || n.includes("lupus anticoag") || n.includes("anti thrombin") || n.includes("protein c") || n.includes("protein s") || n.includes("factor ") || n.includes("sickling") || n.includes("osmotic fragility") || n.includes("pbs") || n.includes("tc,dc") || n.includes("cd4") || n.includes("malaria") || n.includes("filaria") || n.includes("anti-d titer") || n.includes("blood group")) return "🩸";
  if (n.includes("thyroid") || n.includes("tsh") || n.includes("ft3") || n.includes("ft4") || n.includes("anti tpo") || n.includes("anti thyro") || n.includes("thyroglobulin") || n.includes("thyrotropin")) return "🦋";
  if (n.includes("glucose") || n.includes("hba1c") || n.includes("insulin") || n.includes("c peptide") || n.includes("diabetes") || n.includes("homa") || n.includes("ogtt") || n.includes("oral glucose") || n.includes("glucos")) return "🩺";
  if (n.includes("vitamin")) return "💊";
  if (n.includes("urine") || n.includes("urinary") || n.includes("uric acid") || n.includes("creatinine") || n.includes("renal") || n.includes("kidney") || n.includes("gfr") || n.includes("egfr") || n.includes("protein creat") || n.includes("albumin /crat") || n.includes("microalbumin") || n.includes("bun") || n.includes("urea") || n.includes("cystatin") || n.includes("oxalate") || n.includes("stone") || n.includes("urine c/s") || n.includes("urine routine") || n.includes("dysmorphic rbc")) return "🧪";
  if (n.includes("liver") || n.includes("hepatitis") || n.includes("hbsag") || n.includes("hbsab") || n.includes("hbc ") || n.includes("hbe ") || n.includes("hbv") || n.includes("hcv") || n.includes("hev") || n.includes("hav") || n.includes("bilirubin") || n.includes("sgot") || n.includes("sgpt") || n.includes("alt") || n.includes("ast") || n.includes("alp") || n.includes("gamma gt") || n.includes("lft") || n.includes("ldh") || n.includes("albumin") || n.includes("globulin") || n.includes("total protein") || n.includes("ada ") || n.includes("bile acid") || n.includes("ama") || n.includes("lkm") || n.includes("asma") || n.includes("autoimmune hepat")) return "🫀";
  if (n.includes("pcr") || n.includes("ngs") || n.includes("dna") || n.includes("rna") || n.includes("gene") || n.includes("mutation") || n.includes("sequenc") || n.includes("karyotyp") || n.includes("fish") || n.includes("microarray") || n.includes("genotyp") || n.includes("brca") || n.includes("braf") || n.includes("egfr") || n.includes("jak2") || n.includes("huntington") || n.includes("thalassemia") || n.includes("germline") || n.includes("thrombophilia") || n.includes("hnpcc") || n.includes("sca panel") || n.includes("nipt") || n.includes("ugt1a") || n.includes("exome") || n.includes("mthfr") || n.includes("bcr/abl")) return "🧬";
  if (n.includes("biopsy") || n.includes("histopath") || n.includes("ihc") || n.includes("immunohistochem") || n.includes("fnac") || n.includes("cytology") || n.includes("pap smear") || n.includes("lbc") || n.includes("bone marrow") || n.includes("cell block") || n.includes("bone biopsy")) return "🔬";
  if (n.includes("culture") || n.includes("swab c/s") || n.includes("urine c/s") || n.includes("stool c/s") || n.includes("pus culture") || n.includes("blood culture") || n.includes("sputum culture") || n.includes("bal fluid culture") || n.includes("tissue culture") || n.includes("afb culture") || n.includes("fungal culture") || n.includes("bone marrow culture") || n.includes("body fluid cs")) return "🦠";
  if (n.includes("hormone") || n.includes("testosterone") || n.includes("estradiol") || n.includes("progesterone") || n.includes("prolactin") || n.includes("fsh") || n.includes("lh") || n.includes("dhea") || n.includes("cortisol") || n.includes("acth") || n.includes("amh") || n.includes("inhibin") || n.includes("androgen") || n.includes("androstenedione") || n.includes("growth hormone") || n.includes("igf") || n.includes("aldosterone") || n.includes("renin") || n.includes("17-oh") || n.includes("sex horm") || n.includes("dihydrotesto") || n.includes("calcitonin") || n.includes("gastrin") || n.includes("erythropoetin") || n.includes("nt-pro") || n.includes("free beta hcg") || n.includes("beta hcg") || n.includes("double marker") || n.includes("triple marker") || n.includes("quadrouple") || n.includes("inhibin a") || n.includes("inhibin b")) return "⚗️";
  if (n.includes("allergy") || n.includes("ige") || n.includes("immunoglob") || n.includes("iga") || n.includes("igg") || n.includes("igm") || n.includes("immunofix") || n.includes("immunophenotyp") || n.includes("complement") || n.includes(" c3") || n.includes(" c4") || n.includes("celiac") || n.includes("anti ccp") || n.includes("rf quantit") || n.includes("ana ") || n.includes("anca") || n.includes("anti gbm") || n.includes("anti mpo") || n.includes("ena profile") || n.includes("anti cardio") || n.includes("anti phospho") || n.includes("anti pr3") || n.includes("anti smooth") || n.includes("ds dna") || n.includes("scl-70") || n.includes("ss-a") || n.includes("ss-b") || n.includes("centromere") || n.includes("vasculitis") || n.includes("paraneoplast") || n.includes("apla panel") || n.includes("aso ") || n.includes("asma")) return "🛡️";
  if (n.includes("hiv") || n.includes("covid") || n.includes("dengue") || n.includes("typhoid") || n.includes("scrub typhus") || n.includes("leptospira") || n.includes("brucella") || n.includes("malaria") || n.includes("widal") || n.includes("tpha") || n.includes("vdrl") || n.includes("influenza") || n.includes("rubella") || n.includes("toxoplasma") || n.includes("cmv") || n.includes("ebv") || n.includes("hsv") || n.includes("hpv") || n.includes("hepatitis") || n.includes("varicella") || n.includes("mumps") || n.includes("parvo") || n.includes("jev") || n.includes("lyme") || n.includes("filaria") || n.includes("k39") || n.includes("echinococcus") || n.includes("cyctecercosis") || n.includes("neurocysticercosis") || n.includes("hydatid") || n.includes("cryptococcal") || n.includes("aspergillus") || n.includes("filaria") || n.includes("microfilaria") || n.includes("entamoeba")) return "🦠";
  if (n.includes("lipid") || n.includes("cholesterol") || n.includes("hdl") || n.includes("ldl") || n.includes("triglyceride") || n.includes("apolipoprotein") || n.includes("lipoprotein") || n.includes("cardiac") || n.includes("troponin") || n.includes("cpk") || n.includes("bnp") || n.includes("homocysteine")) return "❤️";
  if (n.includes("tumour") || n.includes("tumor") || n.includes("cancer") || n.includes("psa") || n.includes("cea") || n.includes("ca 1") || n.includes("ca 7") || n.includes("ca125") || n.includes("ca19") || n.includes("ca15") || n.includes("afp") || n.includes("beta hcg") || n.includes("cyfra") || n.includes("calcitonin") || n.includes("pdl") || n.includes("msi") || n.includes("her2") || n.includes("er/pr") || n.includes("ki 67") || n.includes("pivka") || n.includes("immunophenotyp") || n.includes("oncomine") || n.includes("leukemia") || n.includes("lymphoma") || n.includes("pnh") || n.includes("jak2") || n.includes("bcr/abl") || n.includes("eosinophilic leukemia") || n.includes("mpn") || n.includes("cytogenetics")) return "🎗️";
  if (n.includes("semen") || n.includes("sperm")) return "🔬";
  if (n.includes("stool") || n.includes("faecal") || n.includes("occult blood") || n.includes("h.pylori antigen") || n.includes("clostridium") || n.includes("reducing sub") || n.includes("hanging drop") || n.includes("stool routine") || n.includes("silver stain")) return "🧫";
  if (n.includes("iron") || n.includes("ferritin") || n.includes("tibc") || n.includes("transferrin") || n.includes("copper") || n.includes("zinc") || n.includes("lead") || n.includes("magnesium") || n.includes("calcium") || n.includes("phosphorus") || n.includes("electrolyte") || n.includes("sodium") || n.includes("potassium") || n.includes("chloride") || n.includes("bicarbonate") || n.includes("osmolarity") || n.includes("fractional excretion")) return "⚗️";
  if (n.includes("drug") || n.includes("digoxin") || n.includes("cyclosporine") || n.includes("tacrolimus") || n.includes("phenytoin") || n.includes("carbamazepine") || n.includes("methotrexate") || n.includes("vancomycin") || n.includes("valporic") || n.includes("lithium") || n.includes("paracetamol") || n.includes("serum digoxin") || n.includes("serum phenytoin") || n.includes("serum lithium")) return "💉";
  if (n.includes("fluid") || n.includes("csf") || n.includes("ascitic") || n.includes("pleural") || n.includes("synovial") || n.includes("body fluid") || n.includes("bal fluid")) return "💧";
  if (n.includes("afb") || n.includes("sputum") || n.includes("mantoux") || n.includes("tb ") || n.includes("tuberculosis") || n.includes("gene xpert") || n.includes("igra") || n.includes("tb gold") || n.includes("tb pcr") || n.includes("neurotropic") || n.includes("respiratory pathogen") || n.includes("pneumocystis") || n.includes("pcp ")) return "🫁";
  if (n.includes("pregnancy") || n.includes("prenatal") || n.includes("nipt") || n.includes("amniotic") || n.includes("double marker") || n.includes("triple marker") || n.includes("quadrouple") || n.includes("free beta hcg") || n.includes("urine preg")) return "🤰";
  if (m.includes("flowcytometry") || m.includes("flow")) return "🔬";
  return "🔬";
}

const SERVICES = [
  ["1,25 DIHYDROXY CHOLECALCIFEROL", 6500, "CLIA", "SERUM", "2ML", "3-5 DAYS"],
  ["17-OH PROGESTERONE", 3000, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["24 HOUR URINARY 5-HYDROXYINDOLEACETICACID (5-HIAA TEST)", 6800, "HPLC", "24 HR URINE", "3ML", "5-7 DAYS"],
  ["24 HOUR URINARY CATECHOLAMINES", 9000, "CHROMATOGRAPHY", "24 HR URINE", "3ML", "5-7 DAYS"],
  ["24 HR URINE METANEPHRINE", 5500, "ELISA", "24 HR URINE", "15ML", "3-5 DAYS"],
  ["24 HRS URINARY ELECTROLYTES", 700, "ISE", "24 HR URINE", "15ML", "SAME DAY"],
  ["24 HRS URINARY AFB", 500, "MICROSCOPY", "24 HR URINE", "15ML", "SAME DAY"],
  ["24 HRS URINARY CALCIUM", 500, "SPECTROPHOTOMETRY", "24 HR URINE", "15ML", "SAME DAY"],
  ["24 HRS URINARY CALCIUM/CREATININE RATIO", 900, "SPECTROPHOTOMETRY", "24 HR URINE", "15ML", "SAME DAY"],
  ["24 HRS URINARY CITRATE", 2800, "SPECTROPHOTOMETRY", "24 HR URINE", "15ML", "3-5 DAYS"],
  ["24 HRS URINARY CREATININE", 600, "SPECTROPHOTOMETRY", "24 HR URINE", "15ML", "SAME DAY"],
  ["24 HRS URINARY PH", 200, "PH METER", "24 HR URINE", "15ML", "SAME DAY"],
  ["24 HRS URINARY PHOSPHORUS", 1000, "SPECTROPHOTOMETRY", "24 HR URINE", "15ML", "SAME DAY"],
  ["24 HRS URINARY PROTEIN", 600, "SPECTROPHOTOMETRY", "24 HR URINE", "15ML", "SAME DAY"],
  ["24 HRS URINARY UREA", 600, "SPECTROPHOTOMETRY", "24 HR URINE", "15ML", "SAME DAY"],
  ["24 HRS URINARY URIC ACID", 300, "SPECTROPHOTOMETRY", "24 HR URINE", "15ML", "SAME DAY"],
  ["24 HRS URINE MICROALBUMIN", 1000, "NEPHELOMETRY", "24 HR URINE", "15ML", "SAME DAY"],
  ["A/G RATIO", 500, "CALCULATION", "SERUM", "2ML", "SAME DAY"],
  ["ABSOLUTE EOSINOPHIL COUNT", 400, "MICROSCOPY", "WHOLE BLOOD EDTA", "3ML", "SAME DAY"],
  ["ACETYLCHOLINESTERASE", 2500, "ENZYMATIC", "WHOLE BLOOD EDTA", "3ML", "5-7 DAYS"],
  ["ACHR (ACETYLCHOLINE RECEPTOR ANTIBODY)", 5500, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["ACID PHOSPHATASE", 1200, "ENZYMATIC", "SERUM", "3ML", "5-7 DAYS"],
  ["ACTH", 2500, "CLIA", "PLASMA EDTA", "3ML", "SAME DAY"],
  ["ADA CSF", 1200, "SPECTROPHOTOMETRY", "CSF", "2ML", "SAME DAY"],
  ["ADA FLUID", 1200, "SPECTROPHOTOMETRY", "FLUID", "2ML", "SAME DAY"],
  ["ADA PUS", 1200, "SPECTROPHOTOMETRY", "PUS", "1ML", "SAME DAY"],
  ["ADA SERUM", 1200, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["AFB CULTURE", 4000, "BACTERIOLOGICAL METHOD", "SPUTUM", "3ML", "4-5 WEEKS"],
  ["AFB STAIN (3 SAMPLES)", 600, "MICROSCOPY", "SPUTUM", "3ML", "SAME DAY"],
  ["AFP (ALPHA FETOPROTEIN)", 1400, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["ALBUMIN, FLUID", 500, "SPECTROPHOTOMETRY", "FLUID", "3ML", "SAME DAY"],
  ["ALBUMIN, SERUM", 250, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["ALBUMIN/CREATININE RATIO (SPOT URINE)", 1100, "SPECTROPHOTOMETRY", "URINE", "5ML", "SAME DAY"],
  ["ALBUMIN PLEURAL FLUID", 500, "SPECTROPHOTOMETRY", "FLUID", "3ML", "SAME DAY"],
  ["ALDOSTERONE LEVEL", 4500, "CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["ALDOSTERONE/RENIN RATIO", 10000, "CLIA", "PLASMA EDTA AND SERUM", "3ML", "3-5 DAYS"],
  ["ALLERGY FOOD AND INHALATION 75 PARAMETER", 12000, "IMMUNOBLOT", "SERUM", "3ML", "NEXT DAY"],
  ["ALLERGY FOOD SCREENING (20 PANEL)", 4000, "IMMUNOBLOT", "SERUM", "3ML", "NEXT DAY"],
  ["ALLERGY INHALATION (20 PANEL)", 4000, "IMMUNOBLOT", "SERUM", "3ML", "NEXT DAY"],
  ["ALLERGY PROFILE (220 PANEL)", 14000, "IMMUNOBLOT", "SERUM", "3ML", "5-7 DAYS"],
  ["ALP", 250, "SPECTROPHOTOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["ALPHA-1 ANTITRYPSIN", 4000, "NEPHELOMETRY", "SERUM", "3ML", "3-5 DAYS"],
  ["AMA (ANTI MITOCHONDRIAL ANTIBODY)", 3000, "ELISA", "SERUM", "3ML", "2-3 DAYS"],
  ["AMA-M2 (M2)", 1600, "ELISA", "SERUM", "3ML", "2-3 DAYS"],
  ["AMH", 3600, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["AMNIOTIC FLUID BY FISH TRISOMY 13,18,21", 16500, "FISH", "AMNIOTIC FLUID", "15-20ML", "2 WEEKS"],
  ["AMYLASE", 500, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["ANA CLIA", 1500, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["ANA IFA", 2000, "IFA", "SERUM", "3ML", "NEXT DAY"],
  ["ANCA/P ANCA/ANTI GBM", 5000, "IMMUNOBLOT", "SERUM", "3ML", "NEXT DAY"],
  ["ANDROGEN", 2500, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["ANDROSTENEDIONE", 4000, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["ANGIOTENSIN CONVERTING ENZYME (ACE)", 2000, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["ANTI TTG IgA", 2300, "CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["ANTI CARDIOLIPIN IgA", 2200, "ELISA/CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["ANTI CARDIOLIPIN IgG", 1600, "ELISA/CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["ANTI CARDIOLIPIN IgM", 1600, "ELISA/CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["ANTI CCP", 2500, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["ANTI DNASE B", 7000, "EIA", "SERUM", "3ML", "5-7 DAYS"],
  ["ANTI GAD-65 ANTIBODY", 7500, "CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["ANTI GBM ANTIBODY", 3000, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["ANTI INSULIN ANTIBODIES", 4000, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["ANTI MPO/PANCA", 2500, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["ANTI MUSK ANTIBODY", 11000, "ELISA", "SERUM", "3ML", "3-5 DAYS"],
  ["ANTI NMO WITH MOG ANTIBODY", 14500, "IFA", "SERUM", "3ML", "3-5 DAYS"],
  ["ANTI PARIETAL CELL ANTIBODY", 5500, "IFA", "SERUM", "3ML", "3-5 DAYS"],
  ["ANTI PHOSPHOLIPID IgG", 2500, "ELISA/CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["ANTI PHOSPHOLIPID IgG & IgM", 4000, "ELISA/CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["ANTI PHOSPHOLIPID IgM", 2500, "ELISA/CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["ANTI PR3/ANCA", 2500, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["ANTI SMOOTH MUSCLE ANTIBODY (ASMA) (IFA)", 3000, "IFA", "SERUM", "3ML", "3-5 DAYS"],
  ["ANTI THROMBIN III ACTIVITY", 6000, "NEPHELOMETRY", "SODIUM CITRATE", "3ML", "5-7 DAYS"],
  ["ANTI THYROGLOBULIN", 2500, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["ANTI TPO", 1800, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["ANTI-AQUAPORIN-4 (NMO-IGG) ANTIBODIES", 12500, "IFA", "SERUM/CSF", "3ML", "5-7 DAYS"],
  ["ANTI-D TITER", 1000, "GEL MATRIX", "SERUM", "3ML", "SAME DAY"],
  ["ANTI-MOG ANTIBODIES", 8000, "IFA", "SERUM/CSF", "3ML", "5-7 DAYS"],
  ["ANTI-NMDA RECEPTOR ENCEPHALITIS IGG ABS", 14500, "IFA", "SERUM", "3ML", "5-7 DAYS"],
  ["ANY FIVE IHC MARKER", 10000, "IHC", "PARAFFIN BLOCK", "—", "10-12 DAYS"],
  ["APLA PANEL (Anti Cardiolipin IgG/IgM, Beta 2 Glycoprotein IgG/IgM, Lupus Anticoagulant)", 8500, "ELISA/COAGULATION", "SERUM AND CITRATE PLASMA", "3ML", "NEXT DAY"],
  ["APOLIPOPROTEIN A1", 1300, "SPECTROPHOTOMETRY", "SERUM", "3ML", "3-5 DAYS"],
  ["APOLIPOPROTEIN B", 1300, "SPECTROPHOTOMETRY", "SERUM", "3ML", "3-5 DAYS"],
  ["APTT", 800, "COAGULATION", "CITRATE PLASMA", "3ML", "SAME DAY"],
  ["ASCITIC FLUID BILIRUBIN (DIRECT)", 250, "SPECTROPHOTOMETRY", "FLUID", "3ML", "SAME DAY"],
  ["ASCITIC FLUID BILIRUBIN (TOTAL)", 250, "SPECTROPHOTOMETRY", "FLUID", "3ML", "SAME DAY"],
  ["ASO QUANTITATIVE", 800, "NEPHELOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["ASPERGILLUS IgM", 4000, "ELISA", "SERUM", "3ML", "3-5 DAYS"],
  ["ASPERGILLUS FUMIGATUS SPECIFIC IgE", 2500, "ImmunoCAP", "SERUM", "3ML", "5-7 DAYS"],
  ["ASPERGILLUS IgE", 2500, "ELISA", "SERUM", "3ML", "3-5 DAYS"],
  ["ASPERGILLUS IgG", 4000, "ELISA", "SERUM", "3ML", "3-5 DAYS"],
  ["AUTOIMMUNE ENCEPHALITIS PANEL", 28000, "IFA", "SERUM", "3ML", "5-7 DAYS"],
  ["AUTOIMMUNE HEPATITIS PANEL", 12500, "IFA", "SERUM", "3ML", "5-7 DAYS"],
  ["AXILLA SWAB C/S", 500, "BACTERIOLOGICAL METHOD", "SWAB", "SWAB", "3 DAYS"],
  ["BAL FLUID CULTURE", 500, "BACTERIOLOGICAL METHOD", "BAL FLUID", "2ML", "3 DAYS"],
  ["BCR/ABL QUANTITATIVE PCR", 12500, "PCR", "WHOLE BLOOD IN EDTA", "6-8ML", "3-5 DAYS"],
  ["BENCE JONES PROTEIN (URINE)", 400, "BIOCHEMICAL", "URINE", "5ML", "SAME DAY"],
  ["BETA 2 MICROGLOBULIN, URINE", 3000, "CLIA", "URINE", "3ML", "3-5 DAYS"],
  ["BETA 2 MICROGLOBULIN, SERUM", 3000, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["BETA HCG TOTAL", 1400, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["BETA-2 GLYCOPROTEIN IgA", 2200, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["BETA-2 GLYCOPROTEIN IgG", 2200, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["BETA-2 GLYCOPROTEIN IgM", 2200, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["BICARBONATE", 1400, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["BILE ACIDS TOTAL", 3500, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["BILIRUBIN, DIRECT", 200, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["BILIRUBIN, TOTAL", 200, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["BIOPSY LARGE", 3500, "MICROSCOPY", "SPECIMEN IN 10% FORMALIN", "—", "5-7 DAYS"],
  ["BIOPSY MEDIUM", 2000, "MICROSCOPY", "SPECIMEN IN 10% FORMALIN", "—", "5-7 DAYS"],
  ["BIOPSY SMALL", 1500, "MICROSCOPY", "SPECIMEN IN 10% FORMALIN", "—", "5-7 DAYS"],
  ["BK VIRUS QUANTITATIVE PCR", 10500, "PCR", "WHOLE BLOOD IN EDTA", "3ML", "5-7 DAYS"],
  ["BLEEDING TIME (BT)", 150, "IVY METHOD", "WALK TO LAB", "—", "SAME DAY"],
  ["BLOOD CULTURE", 600, "BACTERIOLOGICAL METHOD", "SODIUM HEPARIN/BLOOD CULTURE BOTTLE", "3ML", "4-5 DAYS"],
  ["BLOOD GROUPING", 150, "GEL MATRIX", "WHOLE BLOOD IN EDTA", "2ML", "SAME DAY"],
  ["BLOOD UREA NITROGEN (BUN)", 250, "SPECTROPHOTOMETRY", "SERUM/URINE", "2ML", "SAME DAY"],
  ["BODY FLUID CS", 600, "BACTERIOLOGICAL METHOD", "BODY FLUID", "3ML", "3 DAYS"],
  ["BODY FLUID TRIGLYCERIDE", 350, "SPECTROPHOTOMETRY", "BODY FLUID", "3ML", "SAME DAY"],
  ["BONE BIOPSY", 3500, "MICROSCOPY", "SPECIMEN IN 10% FORMALIN", "—", "9-10 DAYS"],
  ["BONE MARROW CULTURE", 1000, "BACTERIOLOGICAL METHOD", "BONE MARROW", "3ML", "3 DAYS"],
  ["BONE MARROW EXAMINATION", 2500, "MICROSCOPY", "BONE MARROW", "3ML", "NEXT DAY"],
  ["BRAF V600E MUTATION", 9500, "PCR & SEQUENCING", "PARAFFIN BLOCK", "—", "3-5 DAYS"],
  ["BRCA PANEL 1&2", 30000, "NGS", "WHOLE BLOOD IN EDTA", "3ML", "3-5 DAYS"],
  ["BRUCELLA ANTIGEN RAPID", 1500, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["BRUCELLA IgG Ab (SPOT)", 800, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["BRUCELLA IgG/IgM ELISA", 4000, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["BRUCELLA IgM Ab (SPOT)", 800, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["C PEPTIDE FASTING", 1500, "CLIA", "FASTING SERUM", "2ML", "SAME DAY"],
  ["C PEPTIDE PP", 1500, "CLIA", "POST PRANDIAL SERUM", "2ML", "SAME DAY"],
  ["C PEPTIDE RANDOM", 1500, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["C1 ESTERASE INHIBITOR", 7000, "EIA", "SERUM", "3ML", "5-7 DAYS"],
  ["C3", 1300, "NEPHELOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["C4", 1300, "NEPHELOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["CA 125", 1500, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["CA 15.3", 1800, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["CA 19.9", 1800, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["CA 72.4", 6000, "CLIA", "SERUM", "2ML", "5-7 DAYS"],
  ["CAG REPEAT MUTATION FOR HUNTINGTON DISEASE", 12500, "NGS", "EDTA WHOLE BLOOD", "3ML", "5-7 DAYS"],
  ["CALCITONIN", 3500, "CLIA", "SERUM", "2ML", "3-5 DAYS"],
  ["CALCIUM", 300, "SPECTROPHOTOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["CARBAMAZEPINE", 1800, "SPECTROPHOTOMETRY", "URINE", "5ML", "NEXT DAY"],
  ["CARDIOLIPIN (IgG & IgM)", 4000, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["CARNITINE, SERUM", 8000, "LCMS/MS", "SERUM", "3ML", "3-5 DAYS"],
  ["CATECHOLAMINE 24 HR URINE", 9000, "HPLC", "24 HR URINE", "50ML", "3-5 DAYS"],
  ["CD4 COUNT", 3500, "FLOWCYTOMETRY", "WHOLE BLOOD IN EDTA", "3ML", "3-5 DAYS"],
  ["CEA", 1500, "CLIA", "SERUM/FLUID", "3ML", "SAME DAY"],
  ["CELIAC PROFILE", 8000, "ELISA", "SERUM", "3ML", "3-5 DAYS"],
  ["CELL BLOCK CYTOLOGY", 1500, "MICROSCOPY", "BODY FLUID", "10-30ML", "3-5 DAYS"],
  ["CENTROMERE B (CB)", 1600, "IMMUNOBLOT", "SERUM", "3ML", "NEXT DAY"],
  ["CERULOPLASMIN", 2000, "SPECTROPHOTOMETRY", "SERUM", "3ML", "NEXT DAY"],
  ["CHLAMYDIA TRACHOMATIS AND NEISSERIA GONORRHOEAE PCR", 7000, "PCR", "VAGINAL SWAB/URINE", "SWAB", "5-7 DAYS"],
  ["CHLAMYDIA TRACHOMATIS IgG ANTIBODY", 2000, "ELISA", "SERUM", "3ML", "3-5 DAYS"],
  ["CHLORIDE", 250, "ISE", "SERUM/URINE/FLUID", "3ML", "SAME DAY"],
  ["CHOLESTEROL", 250, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["CHOLINESTERASE", 2500, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["CHROMOSOMAL MICROARRAY WITH MCC AMNIOTIC FLUID", 27800, "MICROARRAY", "WHOLE BLOOD", "3ML", "5-7 DAYS"],
  ["CLOSTRIDIUM DIFFICILE GDH ANTIGEN", 2500, "ELISA", "STOOL", "2-5G", "SAME DAY"],
  ["CLOSTRIDIUM DIFFICILE TOXIN A/B", 4000, "ELISA", "STOOL", "2-5G", "SAME DAY"],
  ["CLOTTING TIME (CT)", 150, "CAPILLARY", "WALK TO LAB", "—", "SAME DAY"],
  ["CMV IgG/IgM CLIA", 1500, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["CMV PCR QUALITATIVE URINE/BLOOD", 6500, "PCR", "URINE/WHOLE BLOOD EDTA", "5ML", "NEXT DAY"],
  ["CMV PCR QUANTITATIVE BLOOD", 8500, "REAL TIME PCR", "EDTA WHOLE BLOOD", "3ML", "NEXT DAY"],
  ["COMPLETE BLOOD COUNT (CBC)", 500, "COULTER COUNTER", "WHOLE BLOOD IN EDTA", "3ML", "SAME DAY"],
  ["COOMB'S TEST DIRECT", 1000, "AGGLUTINATION METHOD", "WHOLE BLOOD IN EDTA", "2ML", "SAME DAY"],
  ["COPPER 24 HRS URINE", 4000, "SPECTROPHOTOMETRY", "24 HR URINE", "15ML", "3-5 DAYS"],
  ["COPPER SERUM", 3000, "CLIA", "SERUM", "3ML", "5-7 DAYS"],
  ["CORTISOL", 1500, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["CORTISOL - 24 HR. URINE", 1500, "CLIA", "24 HR URINE", "5ML", "SAME DAY"],
  ["COVID-19 ANTIBODY", 1200, "IMMUNOCHROMATOGRAPHY", "SERUM", "2ML", "SAME DAY"],
  ["COVID 19 RT PCR", 2000, "PCR", "NASAL/THROAT SWAB", "SWAB", "SAME DAY"],
  ["CPK MB", 600, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["CPK NAC", 500, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["CREATININE", 250, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["CRP QUANTITATIVE", 700, "NEPHELOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["CRYPTOCOCCAL ANTIGEN", 2500, "IMMUNOCHROMATOGRAPHY", "SERUM/CSF", "2ML", "SAME DAY"],
  ["CSF ACE LEVEL", 3000, "SPECTROPHOTOMETRY", "CSF", "3ML", "3-5 DAYS"],
  ["CSF ROUTINE EXAMINATION", 4000, "SPECTROPHOTOMETRY", "CSF", "3ML", "SAME DAY"],
  ["CYCLOSPORINE LEVEL", 5500, "CLIA", "WHOLE BLOOD IN EDTA", "3ML", "3-5 DAYS"],
  ["CYSTICERCOSIS ELISA", 4000, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["CYFRA 21.1 (Cytokeratin Fragment 21.1)", 7000, "CLIA", "SERUM", "3ML", "5-7 DAYS"],
  ["CYSTATIN C", 3000, "NEPHELOMETRY", "SERUM", "3ML", "5-7 DAYS"],
  ["CYTOGENETICS BONE MARROW", 7500, "CYTOGENETIC", "BONE MARROW SODIUM HEPARIN", "3ML", "5-7 DAYS"],
  ["CYTOLOGY", 1200, "MICROSCOPY", "BODY FLUID", "10-30ML", "NEXT DAY"],
  ["CYTOMEGALOVIRUS QUALITATIVE PCR", 6500, "PCR", "WHOLE BLOOD IN EDTA", "3ML", "NEXT DAY"],
  ["CYTOMEGALOVIRUS QUANTITATIVE PCR", 13000, "PCR", "WHOLE BLOOD IN EDTA", "3ML", "NEXT DAY"],
  ["D-DIMER", 1600, "NEPHELOMETRY", "CITRATE PLASMA", "3ML", "SAME DAY"],
  ["DEHYDROEPIANDROSTERONE (DHEA)", 5000, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["DEHYDROEPIANDROSTERONE SULFATE (DHEAS)", 2000, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["DENGUE SEROLOGY", 1500, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["DIGOXIN LEVEL", 2500, "ELISA", "SERUM", "3ML", "3-5 DAYS"],
  ["DIHYDROTESTOSTERONE (DHT)", 5500, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["DNA TEST (PATERNITY TEST)", 20000, "PCR", "WHOLE BLOOD IN EDTA", "3ML", "7-10 DAYS"],
  ["DOUBLE MARKER", 3600, "CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["DS DNA CLIA", 1800, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["DS DNA IFA", 3000, "IFA", "SERUM", "3ML", "NEXT DAY"],
  ["DYSMORPHIC RBC URINE", 600, "MICROSCOPY", "URINE", "5-10ML", "SAME DAY"],
  ["EBV VCA IgG", 2000, "ELISA", "SERUM", "3ML", "5-7 DAYS"],
  ["EBV VCA IgM", 2000, "ELISA", "SERUM", "3ML", "5-7 DAYS"],
  ["ECHINOCOCCUS IgG ANTIBODY", 4000, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["EGFR (EPIDERMAL GROWTH FACTOR RECEPTOR) GENE", 12500, "PCR & SEQUENCING", "PARAFFIN BLOCK", "—", "7-10 DAYS"],
  ["ELECTROLYTES (Na/K/Cl)", 500, "ISE", "SERUM", "3ML", "SAME DAY"],
  ["ENA PROFILE (18 PARAMETER)", 5500, "IMMUNOBLOT", "SERUM", "3ML", "NEXT DAY"],
  ["ENDOMETRIAL SMEAR", 800, "MICROSCOPY", "SMEAR", "—", "NEXT DAY"],
  ["ENDOMYSIAL ANTIBODY IGA", 5500, "ELISA", "SERUM", "3ML", "3-5 DAYS"],
  ["ENTAMOEBA HISTOLYTICA IgG", 3600, "ELISA", "SERUM", "2ML", "3-5 DAYS"],
  ["EOSINOPHILIC LEUKEMIA PANEL", 25000, "FISH", "WHOLE BLOOD OR EDTA IN SODIUM HEPARIN", "3ML", "5-7 DAYS"],
  ["ER (ESTROGEN RECEPTOR) IHC", 4000, "IHC", "PARAFFIN BLOCK", "3ML", "5-7 DAYS"],
  ["ER/PR/HER2 neu", 7500, "IHC", "PARAFFIN BLOCK", "MINIMUM 1 BLOCK", "5-7 DAYS"],
  ["ER/PR/HER2 neu/Ki67", 8500, "IHC", "PARAFFIN BLOCK", "MINIMUM 1 BLOCK", "5-7 DAYS"],
  ["ERYTHROCYTE SEDIMENTATION RATE (ESR)", 100, "WINTROBE", "WHOLE BLOOD IN EDTA", "3ML", "SAME DAY"],
  ["ERYTHROPOIETIN", 4000, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["ESTRADIOL (E2)/ESTROGEN", 1400, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["EPIDERMAL (PEMPHIGUS) ANTIBODY (IFA)", 9800, "IFA", "SERUM", "3ML", "5-7 DAYS"],
  ["FACTOR II MUTATION STUDY", 8500, "SODIUM CITRATE CLOT BASED", "SODIUM CITRATE", "3ML", "5-7 DAYS"],
  ["FACTOR IX FUNCTIONAL", 4000, "CLOT BASED", "CITRATE PLASMA", "3ML", "3-5 DAYS"],
  ["FACTOR V (GENE MUTATION)", 9000, "SODIUM CITRATE CLOT BASED", "CLOT BASED", "3ML", "5-7 DAYS"],
  ["FACTOR VIII FUNCTIONAL", 4000, "CLOT BASED", "CITRATE PLASMA", "3ML", "3-5 DAYS"],
  ["FAECAL CALPROTECTIN", 4000, "IMMUNOCHROMATOGRAPHY", "STOOL", "2-5G", "SAME DAY"],
  ["FDP", 2000, "COAGULATION", "CITRATE PLASMA", "3ML", "SAME DAY"],
  ["FERRITIN", 1400, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["FIBRINOGEN", 1800, "COAGULATION", "CITRATE PLASMA", "3ML", "SAME DAY"],
  ["FILARIA ANTIGEN", 2000, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["FILARIA IgG/IgM", 1500, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["FITE STAIN FOR M. LEPRAE", 900, "MICROSCOPY", "BODY FLUID", "3ML", "NEXT DAY"],
  ["FLUID AMYLASE", 500, "SPECTROPHOTOMETRY", "FLUID", "3ML", "SAME DAY"],
  ["FLUID CREATININE", 300, "SPECTROPHOTOMETRY", "FLUID", "3ML", "SAME DAY"],
  ["FLUID ROUTINE ANALYSIS", 4500, "SPECTROPHOTOMETRY", "FLUID", "3ML", "SAME DAY"],
  ["FNAC", 1200, "MICROSCOPY", "FNA SLIDE", "FNA SLIDES", "SAME DAY"],
  ["FOLIC ACID", 1800, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["FRACTIONAL EXCRETION OF SODIUM", 2800, "ISE", "SERUM", "3ML", "3-5 DAYS"],
  ["FREE BETA HCG", 2000, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["FSH", 1400, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["FT3", 400, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["FT4", 400, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["FTA ABS", 4000, "UV MICROSCOPY", "SERUM", "3ML", "5-7 DAYS"],
  ["FUNGAL CULTURE", 1000, "MANUAL CULTURE", "SWAB", "SWAB", "3-5 DAYS"],
  ["G6PD", 2200, "CLIA", "WHOLE BLOOD IN EDTA", "3ML", "NEXT DAY"],
  ["GALACTOMANNAN (SERUM)", 8500, "ELISA", "SERUM", "3ML", "3-5 DAYS"],
  ["GAMMA GT", 500, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["GANGLIOSIDE IgG ANTIBODY PANEL", 9000, "ELISA", "SERUM", "3ML", "3-5 DAYS"],
  ["GASTRIN LEVEL", 3000, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["GENE Xpert FOR TUBERCULOSIS (URINE/BODY FLUID)", 4500, "GENE XPERT", "URINE", "3ML", "NEXT DAY"],
  ["GENE Xpert TEST FOR TUBERCULOSIS (SPUTUM)", 4500, "GENE XPERT", "SPUTUM", "3ML", "NEXT DAY"],
  ["GERMLINE MUTATION DETECTION FOR HNPCC", 37000, "PCR", "SERUM/WHOLE BLOOD EDTA", "3ML", "5-7 DAYS"],
  ["GIEMSA STAIN FOR ASPERGILLOSIS", 500, "MICROSCOPY", "FLUID", "3ML", "NEXT DAY"],
  ["GLOBULIN", 250, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["GLOMERULAR FILTRATION RATE (eGFR)", 700, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["GLUCOSE (FASTING)", 80, "SPECTROPHOTOMETRY", "FLUORIDE PLASMA", "2ML", "SAME DAY"],
  ["GLUCOSE (PP)", 80, "SPECTROPHOTOMETRY", "FLUORIDE PLASMA", "2ML", "SAME DAY"],
  ["GLUCOSE (RANDOM)", 80, "SPECTROPHOTOMETRY", "FLUORIDE PLASMA", "2ML", "SAME DAY"],
  ["GLUCOSE 6 PHOSPHATE DEHYDROGENASE", 2200, "ENZYMATIC", "EDTA", "3ML", "5-7 DAYS"],
  ["GONORRHEA ANTIBODY ELISA", 3000, "ELISA", "SERUM", "3ML", "3-5 DAYS"],
  ["GONORRHEA ANTIBODY RAPID", 1500, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["GRAM STAIN", 400, "MICROSCOPY", "FLUID", "3ML", "SAME DAY"],
  ["GROIN SWAB C/S", 500, "BACTERIOLOGICAL METHOD", "SWAB", "SWAB", "3 DAYS"],
  ["GROWTH HORMONE", 2000, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["GROWTH HORMONE STIMULATION TEST", 8000, "CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["H. PYLORI IgM ELISA", 3500, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["H. PYLORI IgG ELISA", 3500, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["H. PYLORI ANTIBODY (SERUM)", 1200, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["H. PYLORI ANTIGEN (STOOL)", 1200, "IMMUNOCHROMATOGRAPHY", "STOOL", "2-5G", "SAME DAY"],
  ["HANGING DROP PREPARATION", 500, "MICROSCOPY", "STOOL", "2-5G", "SAME DAY"],
  ["HAPTOGLOBIN", 3500, "ELISA/CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["HAV IgG ELISA", 1750, "ELISA", "SERUM", "2ML", "NEXT DAY"],
  ["HAV IgG SPOT", 750, "IMMUNOCHROMATOGRAPHY", "SERUM", "2ML", "SAME DAY"],
  ["HAV IgM ELISA", 1750, "ELISA", "SERUM", "2ML", "NEXT DAY"],
  ["HAV IgM SPOT", 750, "IMMUNOCHROMATOGRAPHY", "SERUM", "2ML", "SAME DAY"],
  ["HBA1C", 800, "HPLC", "WHOLE BLOOD IN EDTA", "3ML", "SAME DAY"],
  ["HBV VIRAL LOAD", 6500, "PCR", "WHOLE BLOOD IN EDTA", "3ML", "NEXT DAY"],
  ["HBc IgM Ab (HEPATITIS B CORE ANTIBODY)", 2500, "ELISA", "SERUM", "3ML", "SAME DAY"],
  ["HBc TOTAL ANTIBODY", 2500, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["HBe Ag (HEPATITIS B ENVELOPE ANTIGEN)", 2200, "ELISA", "SERUM", "3ML", "SAME DAY"],
  ["HBsAb (HEPATITIS B SURFACE ANTIBODY)", 2500, "ELISA", "SERUM", "3ML", "SAME DAY"],
  ["HBsAg (SPOT)", 600, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["HBsAg CONFIRMATORY", 2500, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["HBsAg ELISA", 1200, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["HCV ELISA", 1200, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["HCV GENOTYPING", 13000, "PCR", "WHOLE BLOOD IN EDTA", "3ML", "5-7 DAYS"],
  ["HCV SPOT", 600, "IMMUNOCHROMATOGRAPHY", "SERUM", "2ML", "SAME DAY"],
  ["HCV VIRAL LOAD", 6500, "PCR", "WHOLE BLOOD IN EDTA", "3ML", "NEXT DAY"],
  ["HDL", 300, "SPECTROPHOTOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["HEMOGLOBIN ELECTROPHORESIS", 2000, "ELECTROPHORESIS", "WHOLE BLOOD IN EDTA", "3ML", "NEXT DAY"],
  ["HER2/neu - FISH", 17000, "FISH", "PARAFFIN BLOCK", "MINIMUM 1 BLOCK", "5-7 DAYS"],
  ["HER2/neu - IHC", 3500, "IMMUNOHISTOCHEMISTRY", "PARAFFIN BLOCK", "MINIMUM 1 BLOCK", "3-5 DAYS"],
  ["HEV IgG ELISA", 1500, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["HEV IgG SPOT", 750, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["HEV IgM ELISA", 1500, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["HEV IgM SPOT", 750, "IMMUNOCHROMATOGRAPHY", "SERUM", "2ML", "SAME DAY"],
  ["HIV ELISA", 1800, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["HIV P24 ANTIGEN + HIV ANTIBODIES", 1800, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["HIV SPOT", 600, "IMMUNOCHROMATOGRAPHY", "SERUM", "2ML", "SAME DAY"],
  ["HIV VIRAL LOAD", 8500, "PCR", "WHOLE BLOOD IN EDTA", "3ML", "2-3 DAYS"],
  ["HIV WESTERN BLOT", 6500, "IMMUNOBLOT", "SERUM", "3ML", "2-3 DAYS"],
  ["HLA B 51", 9000, "ELISA/CLIA", "WHOLE BLOOD IN EDTA", "3ML", "3-5 DAYS"],
  ["HLA B27 FLOWCYTOMETRY", 4500, "FLOWCYTOMETRY", "SODIUM HEPARIN", "3ML", "3-5 DAYS"],
  ["HLA B27 PCR", 4500, "PCR", "WHOLE BLOOD IN EDTA", "3ML", "NEXT DAY"],
  ["HLA TYPING", 25500, "NGS", "WHOLE BLOOD IN EDTA", "6ML", "2 WEEKS"],
  ["HOMA IR", 2000, "CLIA", "SERUM AND FLUORIDE PLASMA", "3ML", "SAME DAY"],
  ["HOMOCYSTEINE", 2000, "NEPHELOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["HPV WITH LBC SCREEN COMBO", 4500, "PCR/MICROSCOPY", "CERVICAL SWAB", "CERVICAL SWAB", "NEXT DAY"],
  ["HSV 1 AND 2 CLIA", 2500, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["HSV 1 IgG", 1200, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["HSV 1 IgM", 1200, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["HSV 1&2 PCR", 7000, "PCR", "CSF", "3ML", "NEXT DAY"],
  ["HUMAN PAPILLOMAVIRUS (HPV)", 4000, "PCR", "CERVICAL SWAB", "CERVICAL SWAB", "NEXT DAY"],
  ["HUNTINGTON DISEASE MUTATION DETECTION", 12500, "PCR & SEQUENCING", "SERUM/WHOLE BLOOD EDTA", "3ML", "10-12 DAYS"],
  ["HYDATID CYST SCOLEX", 1000, "MICROSCOPY", "HYDATID FLUID", "3-5ML", "NEXT DAY"],
  ["Hs-CRP", 1300, "NEPHELOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["IA2 INSULIN ANTIBODY", 5500, "CLIA", "SERUM", "2ML", "5-7 DAYS"],
  ["IGF-1", 5000, "CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["IHC PANEL CUSTOMIZED", 11500, "IMMUNOHISTOCHEMISTRY", "PARAFFIN BLOCK", "MINIMUM 1 BLOCK", "10-12 DAYS"],
  ["IMMUNOFIXATION ELECTROPHORESIS", 14500, "ELECTROPHORESIS", "SERUM", "3ML", "3-5 DAYS"],
  ["IMMUNOGLOBULIN A (IgA)", 1500, "NEPHELOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["IMMUNOGLOBULIN E (IgE)", 1800, "NEPHELOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["IMMUNOGLOBULIN G (IgG)", 1500, "NEPHELOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["IMMUNOGLOBULIN G4 IgG4", 10000, "NEPHELOMETRY", "SERUM", "3ML", "3-5 DAYS"],
  ["IMMUNOGLOBULIN M (IgM)", 1500, "NEPHELOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["IMMUNOPHENOTYPING LEUKEMIA/LYMPHOMA PANEL", 15000, "FLOWCYTOMETRY", "WHOLE BLOOD IN EDTA/SODIUM HEPARIN", "3ML", "3-5 DAYS"],
  ["INDIA INK PREPARATION", 1500, "MICROSCOPY", "CSF", "2ML", "SAME DAY"],
  ["INFLUENZA (A & B) ANTIGEN", 2500, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["INFLUENZA A H1N1", 5000, "RT PCR", "NASAL/THROAT SWAB", "3ML", "3-5 DAYS"],
  ["INHIBIN A", 2200, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["INHIBIN B", 4000, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["INSULIN FASTING", 1400, "CLIA", "FASTING SERUM", "2ML", "SAME DAY"],
  ["INSULIN PP", 1400, "CLIA", "POST PRANDIAL SERUM", "2ML", "SAME DAY"],
  ["INSULIN RANDOM", 1400, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["INTERLEUKIN-6", 4000, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["INTRINSIC FACTOR ANTIBODY", 3800, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["IONIZED CALCIUM", 700, "ISE", "SERUM", "2ML", "SAME DAY"],
  ["IRON", 700, "SPECTROPHOTOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["IRON PROFILE", 2500, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["ISLET CELL ANTIBODY", 4220, "IFA", "SERUM", "3ML", "5-7 DAYS"],
  ["JAK2 EXON 12 MUTATION", 10500, "PCR", "WHOLE BLOOD IN EDTA", "3ML", "5-7 DAYS"],
  ["JAK2 V617/F MUTATION DETECTION (EXON 14)", 10000, "PCR", "WHOLE BLOOD IN EDTA", "3ML", "3-5 DAYS"],
  ["JEV PCR", 7500, "PCR", "CSF", "2ML", "3-5 DAYS"],
  ["K39 ANTIBODY", 1000, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["KARYOTYPING COUPLE", 9500, "CULTURE/MICROSCOPY AND KARYOTYPE", "SODIUM HEPARIN", "3ML", "2 WEEKS"],
  ["KARYOTYPING FOR CANCER", 6500, "CULTURE/MICROSCOPY AND KARYOTYPE", "SODIUM HEPARIN", "3ML", "2 WEEKS"],
  ["KI 67 IHC", 3500, "IHC", "PARAFFIN BLOCK", "3ML", "5-7 DAYS"],
  ["KOH, TISSUE", 1000, "MICROSCOPY", "TISSUE IN NS", "TISSUE SAMPLE", "SAME DAY"],
  ["KOH BODY FLUID", 500, "MICROSCOPY", "FLUID", "5-10ML", "SAME DAY"],
  ["KOH, SKIN", 1000, "MICROSCOPY", "SKIN", "SKIN SCRAPING", "SAME DAY"],
  ["LACTATE PLASMA", 3000, "SPECTROPHOTOMETRY", "PLASMA EDTA", "2ML", "3-5 DAYS"],
  ["LBC", 1500, "MICROSCOPY", "LBC SPECIMEN", "SAMPLE IN LBC CONTAINER", "NEXT DAY"],
  ["LC-1 (LIVER CYTOSOLIC ANTIGEN TYPE-1 ANTIBODY)", 4500, "ELISA", "SERUM", "3ML", "5-7 DAYS"],
  ["LDH", 500, "SPECTROPHOTOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["LDL", 300, "SPECTROPHOTOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["LEAD BLOOD", 3500, "SPECTROPHOTOMETRY", "WHOLE BLOOD EDTA", "3ML", "3-5 DAYS"],
  ["LEGIONELLA ANTIGEN URINE", 3000, "IMMUNOCHROMATOGRAPHY", "URINE", "5ML", "SAME DAY"],
  ["LEPTOSPIRA ANTIBODY", 1100, "IMMUNOCHROMATOGRAPHY", "SERUM", "2ML", "SAME DAY"],
  ["LEUKEMIA ADVANCE PANEL BY FLOWCYTOMETRY", 17500, "FLOWCYTOMETRY", "WHOLE BLOOD IN EDTA/SODIUM HEPARIN", "3ML EACH", "5-7 DAYS"],
  ["LH", 1400, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["LIPASE", 900, "SPECTROPHOTOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["LIPID PROFILE", 800, "SPECTROPHOTOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["LIPOPROTEIN A", 2000, "NEPHELOMETRY", "SERUM", "3ML", "3-5 DAYS"],
  ["LIVER FUNCTION TEST", 900, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["LKM-1 ANTIBODY", 3500, "IFA", "SERUM", "3ML", "3-5 DAYS"],
  ["LUPUS ANTICOAGULANT", 3000, "COAGULATION", "CITRATED PLASMA", "3ML", "NEXT DAY"],
  ["LYME SEROLOGY", 8500, "ELISA", "SERUM", "3ML", "5-7 DAYS"],
  ["MAGNESIUM", 600, "SPECTROPHOTOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["MALARIA ANTIGEN", 600, "IMMUNOCHROMATOGRAPHY", "WHOLE BLOOD IN EDTA", "3ML", "SAME DAY"],
  ["MALARIA THICK AND THIN SMEAR", 600, "MICROSCOPY", "WHOLE BLOOD IN EDTA", "3ML", "SAME DAY"],
  ["MANTOUX TEST", 600, "HYPERSENSITIVITY", "WALK TO LAB", "—", "72 HRS"],
  ["MEASLES IgG", 3500, "ELISA", "SERUM", "3ML", "3-5 DAYS"],
  ["METANEPHRINE FREE (PLASMA)", 10000, "ELISA", "WHOLE BLOOD IN EDTA", "3ML", "3-5 DAYS"],
  ["METHOTREXATE LEVEL", 6000, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["METHYLMALONIC ACID", 4500, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["MICROALBUMIN, URINE", 800, "NEPHELOMETRY", "URINE", "5ML", "SAME DAY"],
  ["MICROFILARIA ANTIBODY", 2000, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["MPN REFLEX PANEL", 24000, "RT PCR", "WHOLE BLOOD IN EDTA", "6ML", "5-7 DAYS"],
  ["MSI BY IHC", 10000, "IMMUNOHISTOCHEMISTRY", "PARAFFIN BLOCK", "MINIMUM 1 BLOCK", "5-7 DAYS"],
  ["MUMPS IgG", 3500, "ELISA", "SERUM", "3ML", "3-5 DAYS"],
  ["MYOPATHY PANEL", 36000, "NGS", "SERUM", "3ML", "5-7 DAYS"],
  ["NASAL SWAB C/S", 500, "BACTERIOLOGICAL METHOD", "SWAB", "SWAB", "2-3 DAYS"],
  ["NEUROCYSTICERCOSIS IgG ANTIBODY", 4500, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["NEUROTROPIC VIRUS PANEL", 13500, "PCR", "CSF", "3ML", "3-5 DAYS"],
  ["NGS ONCOMINE MYELOID V2GX", 35000, "NGS", "WHOLE BLOOD EDTA", "3ML", "2 WEEKS"],
  ["NIPT", 25000, "NGS", "WHOLE BLOOD IN PAXgene BLOOD TUBE", "10ML", "2 WEEKS"],
  ["NMDA RECEPTOR AB", 14500, "ELISA", "SERUM/CSF", "3ML", "3-5 DAYS"],
  ["NOREPINEPHRINE PLASMA", 8000, "ELISA", "PLASMA EDTA", "3ML", "3-5 DAYS"],
  ["NORMETANEPHRINE 24 HR URINE", 9000, "ELISA", "24 HRS URINE", "50ML", "3-5 DAYS"],
  ["NT-PRO BNP", 3500, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["OCCULT BLOOD STOOL", 300, "IMMUNOCHROMATOGRAPHY", "STOOL", "3-5G", "SAME DAY"],
  ["OLIGOCLONAL BAND WITH IGG INDEX", 10000, "ELECTROPHORESIS", "SERUM/CSF", "3ML EACH", "7-10 DAYS"],
  ["ORAL GLUCOSE CHALLENGE TEST", 200, "SPECTROPHOTOMETRY", "FLUORIDE PLASMA", "2ML", "SAME DAY"],
  ["ORAL GLUCOSE TOLERANCE TEST", 200, "SPECTROPHOTOMETRY", "FLUORIDE PLASMA", "2ML", "SAME DAY"],
  ["OSMOLARITY SERUM", 1500, "ISE/CALCULATION", "SERUM", "3ML", "SAME DAY"],
  ["OSMOTIC FRAGILITY", 2000, "MANUAL METHOD", "SODIUM HEPARIN", "3ML", "3-5 DAYS"],
  ["OXALATE 24 HRS URINE", 6000, "SPECTROPHOTOMETRY", "24 HR URINE", "15ML", "3-5 DAYS"],
  ["PAP SMEAR", 800, "MICROSCOPY", "CERVICAL SMEAR", "SLIDES", "NEXT DAY"],
  ["PARACETAMOL", 2500, "SPECTROPHOTOMETRY", "SERUM", "3ML", "NEXT DAY"],
  ["PARANEOPLASTIC PANEL (12 PARAMETERS)", 15000, "IMMUNOBLOT", "SERUM", "3ML", "NEXT DAY"],
  ["PARVO VIRUS IgG/IgM", 9000, "ELISA", "SERUM", "3ML", "3-5 DAYS"],
  ["PAS STAIN", 800, "MICROSCOPY", "FLUID/SPUTUM", "SAMPLE IN STERILE CONTAINER", "NEXT DAY"],
  ["PBS", 500, "MICROSCOPY", "WHOLE BLOOD EDTA", "2ML", "SAME DAY"],
  ["PCOD PANEL (LH, FSH, PRL, TESTO TOTAL, INSULIN FASTING, GLUCOSE FASTING, TSH)", 6500, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["PCOS PANEL (LH, FSH, PRL, TESTO TOTAL, INSULIN FASTING, GLUCOSE FASTING, TFT, DHEAS)", 8500, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["PDL 1 BY DAKO", 15000, "IMMUNOHISTOCHEMISTRY", "FFPE TISSUE BLOCK", "AT LEAST 1 PARAFFIN BLOCK", "5-7 DAYS"],
  ["PDL-1 (SP263)", 11500, "IHC", "PARAFFIN BLOCK", "MINIMUM 1 BLOCK", "7-10 DAYS"],
  ["PHENYTOIN", 2000, "SPECTROPHOTOMETRY", "SERUM", "3ML", "NEXT DAY"],
  ["PHOSPHORUS", 500, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["PIVKA II, DES-GAMMA CARBOXY PROTHROMBIN (DCP)", 6500, "CLIA", "SERUM", "3ML", "5-7 DAYS"],
  ["PLA-2 RECEPTOR ANTIBODY", 11500, "ELISA", "SERUM", "3ML", "NEXT DAY"],
  ["PLASMA RENIN", 9500, "ELISA", "PLASMA EDTA", "3ML", "3-5 DAYS"],
  ["PLASMA RENIN ACTIVITY", 10000, "EIA", "SERUM/PLASMA EDTA", "3ML", "5-7 DAYS"],
  ["PLEURAL FLUID ROUTINE ANALYSIS", 4500, "MICROSCOPY", "FLUID", "3ML", "SAME DAY"],
  ["PNEUMOCYSTIS PNEUMONIA (PCP)", 7000, "PCR", "BAL FLUID", "3ML", "5-7 DAYS"],
  ["PNH WITH FLAER", 8000, "FLOWCYTOMETRY", "WHOLE BLOOD EDTA", "3ML", "5-7 DAYS"],
  ["PR (PROGESTERONE RECEPTOR) IHC", 4000, "IHC", "PARAFFIN BLOCK", "AT LEAST 1 PARAFFIN BLOCK", "5-7 DAYS"],
  ["PROCALCITONIN", 2500, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["PROGESTERONE", 1500, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["PROLACTIN", 1500, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["PORPHOBILINOGEN URINARY", 6500, "SPECTROPHOTOMETRY", "URINE", "10ML", "3-5 DAYS"],
  ["PROTEIN CSF", 500, "SPECTROPHOTOMETRY", "CSF", "1ML", "SAME DAY"],
  ["PROTEIN C", 7500, "CHROMOGENIC METHOD", "CITRATED PLASMA", "3ML", "3-5 DAYS"],
  ["PROTEIN CREATININE RATIO (SPOT URINE)", 700, "SPECTROPHOTOMETRY", "URINE", "5ML", "SAME DAY"],
  ["PROTEIN ELECTROPHORESIS", 1700, "ELECTROPHORESIS", "SERUM", "3ML", "3-5 DAYS"],
  ["PROTEIN FLUID", 500, "SPECTROPHOTOMETRY", "FLUID", "1ML", "SAME DAY"],
  ["PROTEIN S ACTIVITY", 7500, "CLOT BASED", "CITRATE PLASMA", "3ML", "3-5 DAYS"],
  ["PROTEIN URINE", 500, "SPECTROPHOTOMETRY", "URINE", "10ML", "SAME DAY"],
  ["PROTHROMBIN TIME", 600, "COAGULATION", "CITRATE PLASMA", "2ML", "SAME DAY"],
  ["PSA", 1500, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["PSA FREE", 2000, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["PTH", 2500, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["PUS CULTURE", 500, "BACTERIOLOGICAL METHOD", "PUS", "1ML", "3 DAYS"],
  ["QUADRUPLE MARKER", 5500, "CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["REDUCING SUBSTANCE STOOL", 400, "BIOCHEMICAL", "STOOL", "2-5G", "SAME DAY"],
  ["RENAL FUNCTION TEST", 900, "SPECTROPHOTOMETRY", "SERUM", "3ML", "SAME DAY"],
  ["RESPIRATORY PATHOGEN PCR PANEL", 14500, "RT PCR", "NASAL/THROAT SWAB", "SWAB IN VTM", "5-7 DAYS"],
  ["RETICULOCYTE COUNT", 500, "MICROSCOPY", "WHOLE BLOOD IN EDTA", "2ML", "SAME DAY"],
  ["RF QUANTITATIVE", 700, "NEPHELOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["RUBELLA IgG", 1500, "CLIA", "SERUM", "2ML", "NEXT DAY"],
  ["RUBELLA IgG/IgM", 3000, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["RUBELLA IgM", 1500, "CLIA", "SERUM", "2ML", "NEXT DAY"],
  ["SCA PANEL", 24900, "PCR", "SERUM", "3ML", "5-7 DAYS"],
  ["SCL-70 (SCLERODERMA) ANTIBODY", 2500, "IMMUNOBLOT", "SERUM", "3ML", "NEXT DAY"],
  ["SCRUB TYPHUS ANTIBODY", 1500, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["SEMEN ANALYSIS", 500, "MICROSCOPY", "SEMEN", "3ML", "SAME DAY"],
  ["SERUM CATECHOLAMINE", 20000, "HPLC", "SERUM", "3ML", "5-7 DAYS"],
  ["SERUM DIGOXIN LEVEL", 2000, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["SERUM LITHIUM", 1400, "SPECTROPHOTOMETRY", "SERUM", "3ML", "NEXT DAY"],
  ["SERUM OSMOLARITY", 1300, "CALCULATION", "SERUM", "3ML", "SAME DAY"],
  ["SERUM PHENYTOIN", 2500, "SPECTROPHOTOMETRY", "SERUM", "3ML", "NEXT DAY"],
  ["SERUM TRYPTASE", 4000, "ELISA", "SERUM", "3ML", "3-5 DAYS"],
  ["SEX HORMONE BINDING GLOBULIN", 4800, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["SGOT/AST", 250, "SPECTROPHOTOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["SGPT/ALT", 250, "SPECTROPHOTOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["SICKLING TEST", 800, "MICROSCOPY", "WHOLE BLOOD IN EDTA", "2ML", "SAME DAY"],
  ["SILVER STAINING FOR CRYPTOSPORIDIOSIS", 500, "MICROSCOPY", "SERUM", "2ML", "NEXT DAY"],
  ["SPOT URINARY ELECTROLYTES", 700, "ISE", "URINE", "2ML", "SAME DAY"],
  ["SPUTUM CULTURE", 500, "BACTERIOLOGICAL METHOD", "SPUTUM", "2ML", "3 DAYS"],
  ["SPUTUM FOR PNEUMOCYSTIS CARINII", 700, "MICROSCOPY", "SPUTUM", "2ML", "SAME DAY"],
  ["SPUTUM KOH PREPARATION", 500, "MICROSCOPY", "SPUTUM", "2ML", "SAME DAY"],
  ["SS-A/RO ANTIBODY", 2500, "IMMUNOBLOT", "SERUM", "2ML", "NEXT DAY"],
  ["SS-B/LA ANTIBODY", 2500, "IMMUNOBLOT", "SERUM", "2ML", "NEXT DAY"],
  ["STONE ANALYSIS", 2500, "SPECTROPHOTOMETRY", "STONE SAMPLE", "STONE SAMPLE", "3-5 DAYS"],
  ["STOOL C/S", 600, "BACTERIOLOGICAL METHOD", "STOOL", "2-5G", "3 DAYS"],
  ["STOOL ROUTINE EXAMINATION", 150, "MICROSCOPY", "STOOL", "2-5G", "SAME DAY"],
  ["STREPTOCOCCAL ANTIGEN URINE", 3000, "IMMUNOCHROMATOGRAPHY", "URINE", "2ML", "SAME DAY"],
  ["SWAB C/S", 600, "BACTERIOLOGICAL METHOD", "SWAB", "SWAB", "3 DAYS"],
  ["SYNOVIAL FLUID ROUTINE ANALYSIS", 4500, "SPECTROPHOTOMETRY", "SYNOVIAL FLUID", "2ML", "SAME DAY"],
  ["TACROLIMUS", 3500, "CLIA", "WHOLE BLOOD IN EDTA", "3ML", "SAME DAY"],
  ["TB GOLD, INTERFERON GAMMA RELEASE ASSAY (IGRA)", 4600, "CLIA", "LITHIUM HEPARIN", "4ML", "NEXT DAY"],
  ["TB PCR", 3500, "PCR", "CSF/SPUTUM/URINE/BODY FLUID", "2ML", "NEXT DAY"],
  ["TC, DC FLUID", 500, "COULTER COUNTER", "FLUID IN EDTA", "2ML", "SAME DAY"],
  ["TESTOSTERONE FREE", 2300, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["TESTOSTERONE TOTAL", 1500, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["THALASSEMIA COMPLETE PANEL", 25000, "PCR", "WHOLE BLOOD IN EDTA", "3ML", "7-10 DAYS"],
  ["THROAT SWAB C/S", 600, "BACTERIOLOGICAL METHOD", "SWAB", "SWAB", "3 DAYS"],
  ["THROMBOCHECK PANEL (PROTEIN C, PROTEIN S, ANTITHROMBIN III, HOMOCYSTEINE, FACTOR V)", 26000, "CLIA, CLOT BASED", "SERUM, WHOLE BLOOD EDTA, CITRATE PLASMA", "3ML EACH", "5-7 DAYS"],
  ["THROMBOPHILIA PANEL (PROTEIN C, PROTEIN S, ANTITHROMBIN ACTIVITY, FACTOR V LEIDEN MUTATION, MTHFR GENE MUTATION, PROTHROMBIN GENE MUTATION)", 32000, "PCR, CLOT BASED", "SERUM, EDTA, AND CITRATE PLASMA", "3ML EACH", "5-7 DAYS"],
  ["THYROGLOBULIN", 3000, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["THYROID FUNCTION TEST (FREE)", 1000, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["THYROTROPIN RECEPTOR ANTIBODY", 3500, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["TISSUE CULTURE", 800, "BACTERIOLOGICAL METHOD", "TISSUE IN NS", "TISSUE IN STERILE NS CONTAINER", "3 DAYS"],
  ["TISSUE TRANSGLUTAMINASE TTG IgA", 2500, "ELISA", "SERUM", "2ML", "NEXT DAY"],
  ["TORCH PANEL", 4500, "CLIA", "SERUM", "2ML", "NEXT DAY"],
  ["TOTAL IRON BINDING CAPACITY (TIBC)", 700, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["TOTAL PROTEIN", 300, "SPECTROPHOTOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["TOXOPLASMA IgG", 1500, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["TOXOPLASMA IgM", 1500, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["TPHA", 400, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["TPHA TITRE", 1400, "HEMAGGLUTINATION", "SERUM", "3ML", "SAME DAY"],
  ["TRIGLYCERIDE", 250, "SPECTROPHOTOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["TRIPLE MARKER", 4500, "CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["TROPONIN I QUALITATIVE", 1000, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["TROPONIN I QUANTITATIVE", 3500, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["TSH", 400, "CLIA", "SERUM", "2ML", "SAME DAY"],
  ["TSH RECEPTOR ANTIBODY", 5500, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["TYPHOID IgG & IgM", 1500, "IMMUNOCHROMATOGRAPHY", "SERUM", "3ML", "SAME DAY"],
  ["UDP GLUCURONOSYLTRANSFERASE FAMILY 1 (UGT1A1)", 11500, "PCR", "WHOLE BLOOD IN EDTA", "3ML", "5-7 DAYS"],
  ["UREA", 250, "SPECTROPHOTOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["URIC ACID", 250, "SPECTROPHOTOMETRY", "SERUM", "2ML", "SAME DAY"],
  ["URINARY CREATININE", 500, "SPECTROPHOTOMETRY", "URINE", "5ML", "SAME DAY"],
  ["URINARY GLYCOSAMINOGLYCAN GAG", 2500, "SPECTROPHOTOMETRY", "URINE", "5ML", "3-5 DAYS"],
  ["URINARY POTASSIUM", 350, "ISE", "URINE", "5ML", "SAME DAY"],
  ["URINARY SODIUM", 350, "ISE", "URINE", "5ML", "SAME DAY"],
  ["URINE BILE SALT", 500, "BIOCHEMICAL", "URINE", "5ML", "SAME DAY"],
  ["URINE C/S", 500, "BACTERIOLOGICAL METHOD", "URINE", "5ML", "3 DAYS"],
  ["URINE CALCIUM CREATININE RATIO", 1000, "SPECTROPHOTOMETRY", "URINE", "5ML", "SAME DAY"],
  ["URINE FAT GLOBULES", 150, "BIOCHEMICAL", "URINE", "5ML", "SAME DAY"],
  ["URINE KETONE BODIES", 100, "BIOCHEMICAL", "URINE", "5ML", "SAME DAY"],
  ["URINE MULTIDRUG PANEL (12 PARAMETERS)", 4000, "IMMUNOCHROMATOGRAPHY", "URINE", "5ML", "SAME DAY"],
  ["URINE OSMOLARITY", 1300, "ISE/CALCULATION", "URINE", "5ML", "SAME DAY"],
  ["URINE PREGNANCY TEST", 200, "IMMUNOCHROMATOGRAPHY", "URINE", "5ML", "SAME DAY"],
  ["URINE PROTEIN ELECTROPHORESIS", 4000, "ELECTROPHORESIS", "URINE", "5ML", "3-5 DAYS"],
  ["URINE ROUTINE EXAMINATION", 150, "MICROSCOPY", "URINE", "5ML", "SAME DAY"],
  ["URINE UROBILINOGEN", 200, "BIOCHEMICAL", "URINE", "5ML", "SAME DAY"],
  ["VACCICHECK PANEL", 11500, "CLIA", "SERUM", "3ML", "5-7 DAYS"],
  ["VALPROIC ACID", 2000, "CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["VANCOMYCIN", 3000, "CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["VARICELLA ZOSTER VIRUS IgG", 3000, "ELISA/CLIA", "SERUM", "3ML", "NEXT DAY"],
  ["VASCULITIS PANEL", 9800, "IMMUNOBLOT", "SERUM", "3ML", "5-7 DAYS"],
  ["VDRL CSF", 800, "FLOCCULATION", "CSF", "3ML", "SAME DAY"],
  ["VDRL SERUM", 500, "FLOCCULATION", "SERUM", "3ML", "SAME DAY"],
  ["VITAMIN A", 8500, "CLIA", "FASTING SERUM", "3ML", "3-5 DAYS"],
  ["VITAMIN B12", 1600, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["VITAMIN B6", 6000, "CLIA", "FASTING SERUM", "3ML", "3-5 DAYS"],
  ["VITAMIN B7", 9000, "CLIA", "SERUM", "3ML", "3-5 DAYS"],
  ["VITAMIN C", 7500, "CLIA", "FASTING SERUM", "3ML", "3-5 DAYS"],
  ["VITAMIN D", 2200, "CLIA", "SERUM", "3ML", "SAME DAY"],
  ["VITAMIN E", 7500, "CLIA", "FASTING SERUM", "3ML", "3-5 DAYS"],
  ["VITAMIN K1", 11000, "CLIA", "FASTING SERUM", "3ML", "3-5 DAYS"],
  ["VMA 24 HRS URINE", 5000, "SPECTROPHOTOMETRY", "24 HR URINE", "15ML", "3-5 DAYS"],
  ["VON WILLEBRAND FACTOR", 18500, "ENZYME IMMUNOASSAY", "CITRATE PLASMA", "3ML", "5-7 DAYS"],
  ["WHOLE EXOME SEQUENCING", 42000, "NGS", "WHOLE BLOOD IN EDTA", "4ML", "4 WEEKS"],
  ["WIDAL TEST", 400, "AGGLUTINATION", "SERUM", "3ML", "SAME DAY"],
  ["ZINC SERUM", 4000, "SPECTROPHOTOMETRY", "SERUM", "3ML", "3-5 DAYS"],
];

async function main() {
  console.log(`🌱 Seeding ${SERVICES.length} services...`);

  await prisma.service.deleteMany();

  const data = SERVICES.map(([title, price, method, sample, volume, tat], i) => ({
    title: title as string,
    description: `Method: ${method} | Sample: ${sample} | Volume: ${volume} | TAT: ${tat}`,
    price: price as number,
    icon: getIcon(title as string, method as string),
    featured: false,
    order: i + 1,
  }));

  // Insert in batches of 100 to avoid hitting limits
  for (let i = 0; i < data.length; i += 100) {
    await prisma.service.createMany({ data: data.slice(i, i + 100) });
    console.log(`  ✓ Inserted ${Math.min(i + 100, data.length)} / ${data.length}`);
  }

  console.log(`✅ Done — ${data.length} services seeded.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
